color_list_1 = set(["White", "Black", "Red"])
color_list_2 = set(["Red", "Green","orange"])
print("The colors are:")
print(color_list_1)
print(color_list_2)
print("\nList of colors present in list1 and not in list2:")
print(color_list_1.difference(color_list_2))
